### ISSUE TITLE
Interested in Helping with Another Collection?

### ISSUE THREAD

**Issue by jrg94** [MariusGarbea/Nick#12]
Hey! I just stumbled upon your repo, and I noticed it hasn't been maintained in awhile. I'm very interested in what you've started here, and I was wondering if you wanted to transfer some of your work over to a active repo called [Sample Programs](https://github.com/jrg94/sample-programs). 

Sample Programs is basically just a massive collection of programs in as many languages as possible. I think we're up to 80 or so languages at the moment and over 100 code snippets. Currently, the repo doesn't support factorial, so I figured you _might_ be interested in being the first contributor.

Also, I noticed that all your scripts solve factorial iteratively, but I know it's also common to do it recursively. Perhaps, we could incorporate both in the repo.

**Comment by MariusGarbea** [comment]
Hey @jrg94, I would be happy to contribute, thanks for reaching out

**Comment by jrg94** [comment]
Sounds great! I'll get you added to the org.
